#cloud-config
# controller nodes typically don't have an additional disk

package_update: true
package_upgrade: true
package_reboot_if_required: true

groups:
  - admingroup: [root,sys,ubuntu]

users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    homedir: /home/ubuntu
    shell: /bin/bash
    lock_passwd: true
    ssh_authorized_keys: 
      - <SSH_PUBLIC_KEY>

packages:
  - curl
  - apt-transport-https
  - ca-certificates
  - software-properties-common
  - wget
  - git
  - iptables
  - open-iscsi
  - nfs-common
  - cryptsetup
  - dmsetup
  - lvm2
  - qemu-guest-agent
  - qemu-utils

runcmd:
  - ufw --force disable
  - ufw --force reset
  - snap install btop
  - - systemctl
    - enable
    - --now
    - qemu-guest-agent.service